CREATE TABLE CASO_USO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    CODIGO VARCHAR2(20),
    NOMBRE VARCHAR2(100),
    ACTOR VARCHAR2(50),
    TIPO VARCHAR2(20),
    COMPLEJIDAD VARCHAR2(20),
    DESCRIPCION VARCHAR2(400),
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

COMMIT;

CREATE OR REPLACE PROCEDURE SP_INSERTAR_CASO_USO (
    P_CODIGO       IN VARCHAR2,
    P_NOMBRE       IN VARCHAR2,
    P_ACTOR        IN VARCHAR2,
    P_TIPO         IN VARCHAR2,
    P_COMPLEJIDAD  IN VARCHAR2,
    P_DESCRIPCION  IN VARCHAR2
) AS
BEGIN
    INSERT INTO CASO_USO
    (CODIGO, NOMBRE, ACTOR, TIPO, COMPLEJIDAD, DESCRIPCION)
    VALUES
    (P_CODIGO, P_NOMBRE, P_ACTOR, P_TIPO, P_COMPLEJIDAD, P_DESCRIPCION);

    COMMIT;
END;
/

COMMIT;